name: "Test validator"
on: 
    pull_request:
        paths:
            - 'tools/openchain_telco_sbom_validator/**'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
        TERM: dumb
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Building environment
      run: | 
        cd tools/openchain_telco_sbom_validator/
        python3 -m venv .env
        cd testing/
        wget https://raw.githubusercontent.com/thorsteinssonh/bash_test_tools/master/bash_test_tools 
    - name: Run tests
      run: | 
        cd tools/openchain_telco_sbom_validator/testing/
        ./test-test.sh